version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: dla_postgres_dev
    environment:
      POSTGRES_DB: dla_access_enterprise
      POSTGRES_USER: dla
      POSTGRES_PASSWORD: dla_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: dla_redis_dev
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: dla_rabbitmq_dev
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
