"""add_dotacion_table

Revision ID: 95f732f3c8b3
Revises: e50c5e9defca
Create Date: 2026-07-24 15:12:50.491711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f732f3c8b3'
down_revision: Union[str, None] = 'e50c5e9defca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_dotaciones',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_dotaciones_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_dotaciones'))
    )
    op.create_index(op.f('ix_employee_dotaciones_employee_id'), 'employee_dotaciones', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_dotaciones_employee_id'), table_name='employee_dotaciones')
    op.drop_table('employee_dotaciones')
    # ### end Alembic commands ###
